const fs = require('fs');
const path = require('path');
const xlsx = require('xlsx');

const testDataDir = path.join(__dirname, '..', 'test_data');

if (!fs.existsSync(testDataDir)) {
  fs.mkdirSync(testDataDir);
}

// 1. Messy CSV (blank rows, title row, then headers)
const messyCsvData = `


MONTHLY VENDOR SPEND REPORT

Vendor ID,Company Name,Contact Email,Invoice Total,PO Total
V001,Acme Corp,acme@test.com,5000,6000
V002,Globex,globex@test.com,12000,10000
`;
fs.writeFileSync(path.join(testDataDir, 'Messy_Headers_Test.csv'), messyCsvData.trimStart());

// 2. Complex Excel with metadata and empty rows
const wb = xlsx.utils.book_new();

const sheetData = [
  ["SMARTBRIDGE FINANCIAL EXPORT"],
  ["Generated On: 2026-06-13"],
  ["Generated By: System Admin"],
  [],
  ["This report contains all vendor spend data for Q2. Do not distribute."],
  [],
  // Actual Headers
  ["Supplier ID", "Supplier Name", "City and State", "Nation", "Target Spend", "Transactions", "Due Total"],
  // Data
  ["S100", "Initech", "Austin TX", "USA", 50000, 15, 2000],
  ["S101", "Soylent", "New York NY", "USA", 75000, 42, 0]
];

const ws = xlsx.utils.aoa_to_sheet(sheetData);
xlsx.utils.book_append_sheet(wb, ws, "Vendor Data");

xlsx.writeFile(wb, path.join(testDataDir, 'Complex_Metadata_Test.xlsx'));

// 3. Dense non-header top row (challenging case)
const trickyCsvData = `
Total Spend:,150000,Total Vendors:,45
Report Status:,FINAL,Period:,Q3
,,,
Vendor Number,Vendor Name,Street,Zip Code,Curr
99912,Stark Industries,10880 Malibu Point,90265,USD
`;
fs.writeFileSync(path.join(testDataDir, 'Tricky_Dense_Top_Test.csv'), trickyCsvData.trimStart());

console.log("Header detection test files generated successfully in test_data/");
